env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=10LNOH9CRu3iwHctMvCNEoqYm71uohNWy

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
