env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=XB8hRruLUYeUf7nAfOdBzg9uhriiwM0nL

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
